name: ci/cd main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # Docker Image 빌드
      - name: Build Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memoir_frontend .
          docker push ${{ secrets.DOCKER_USERNAME }}/memoir_frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 서버에서 Docker 이미지 실행
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f ${{ secrets.DOCKER_USERNAME }}/memoir_frontend
            docker rmi ${{ secrets.DOCKER_USERNAME }}/memoir_frontend
            docker pull ${{ secrets.DOCKER_USERNAME }}/memoir_frontend
            docker run -d -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/memoir_frontend
